### ISSUE TITLE
"aws elbv2 create-target-group" command fails in GitBash on Win10

### ISSUE THREAD

**Issue by vgribok** [aws-samples/modernization-unicorn-store#5]
FYI: likely not a workshop bug, but the issue requires a workaround:
I ran the workshop locally, on Windows 10 laptop. When working through steps described in [fargate.md](../tree/master/content/secrets/fargate.md), I saw that `aws elbv2 create-target-group --name ecs-Unicor-UnicornStore-Service --protocol HTTP --port 80 --vpc-id $UnicornVPCID --health-check-path "/health" --target-type ip` command, when run in GitBash, failed with "_An error occurred (ValidationError) when calling the CreateTargetGroup operation: Health check path 'C:/Program Files/Git/health' must begin with a '/' character and can only contain printable ASCII characters, without spaces_" error. 

**The work-around**: run the same command in CMD shell, after small alterations, like replacing $ENVVAR format with %ENVVAR%:
```
aws elbv2 create-target-group --name ecs-Unicor-UnicornStore-Service --protocol HTTP --port 80 --vpc-id %UnicornVPCID% --health-check-path "/health" --target-type ip
```

**Comment by CarmenAPuccio** [comment]
@vgribok thanks for catching this. I'm going to be writing the run the workshop locally instructions and we can table this until then. Closing for now.
